#!/bin/bash
#Author: Balguissa Ouedraogo
#Date: October 20 2022
#Description: code to install some packages in Centos (linux)
yum install wget -y
yum install net-tools -y
yum install sysstat -y
yum inatall finger -y
yum install gcc -y
yum install make -y 
yum install python3 -y 
yum install epel-release -y 
yum install git -y 

echo "installation done successfully"
